Services:
    db:
      build:
        context: ./MySQL
        dockerfile: Dockerfile
      container_name: database
      restart: always
      ports:
        - 3306:3306
      volumes:
        - ./MySQL/volumes:/var/lib/mysql
      hostname: eam_database                                                                                  
      networks:                                                                                               
        - net_eam_database                                                                                    
      healthcheck:                                                                                            
          test: ["CMD","mysql", "-u", "root", "-proot"]                                                       
          interval: 30s                                                                                       
          timeout: 10s                                                                                        
          retries: 5                                                                                          
 # --------------------------------------------------------------------                                      
  # - The adminer is a tool for managing content in databases.                                              
    adminer:                                                                                                  
      image: adminer                                                                                          
      container_name: adminer_eam                                                                             
      restart: always                                                                                         
      ports:                                                                                                  
        - 8080:8080                                                                                           
      networks:                                                                                               
        - net_eam_database               
 # --------------------------------------------------------------------
  # - fastapi refers to the container where the application backend will be stored.
      fastapi:
       build: 
       context: ./FastAPI/app
       dockerfile: Dockerfile
      container_name: backend
      restart: always
      ports:
         - "8000:80"
      depends_on:
        db:
          condition: service_healthy
      networks:
        - net_eam_database
 # --------------------------------------------------------------------
    networks:
      net_eam_database:
        driver: bridge
        name: net_eam_database
